### PR TITLE
Fix autorestart option for windows agent (which broke everything else)

### LINKED ISSUE #1351: [config] autorestart flag expected not present on windows
```
Python could not construct the class instance 
Traceback (most recent call last):
  File "win32\agent.pyc", line 47, in __init__
  File "config.pyc", line 431, in get_config
AttributeError: Values instance has no attribute 'autorestart' 
%2: %3
```
This the current master pre-5.2 release 7a4294fe7b09df939b8c03a6ff47dedaf7a60ce4.
Introduced by f62d32900ebd2a33e3c7280345e71c22dcee13fe.

### PR DESCRIPTION
**Pull request by degemer**
Fixes #1351.
Replaces #1352.

### CODE REVIEW

**Comment by LeoCavaille** [comment]
Thanks
