### ISSUE TITLE
hdfs_namenode error

### ISSUE THREAD

**Issue by sammerry** [DataDog/dd-agent#3680]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

status
```
====================
Collector (v 5.22.0)
====================

  Status date: 2018-02-15 10:01:07 (6s ago)
  Pid: 82478
  Platform: Linux-4.4.35-33.55.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: -0.0019 s
    System UTC time: 2018-02-15 10:01:13.692841
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: Not found

    hdfs_namenode (1.2.0)
    ---------------------
      - instance #0 [ERROR]: "'NoneType' object has no attribute 'append'"
      - Collected 0 metrics, 0 events & 0 service checks
```

collector exception
```
2018-02-15 09:34:39 UTC | ERROR | dd.collector | checks.hdfs_namenode(__init__.py:829) | Check 'hdfs_namenode' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 812, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/hdfs_namenode/hdfs_namenode.py", line 99, in check
    tags.append('namenode_url:' + jmx_address)
```

**Additional environment details (Operating System, Cloud provider, etc):**

uname -a
```
<host>.amzn1.x86_64 #1 SMP Tue Dec 6 20:30:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

`/etc/dd-agent/conf.d/hdfs_namenode.yaml`
```
init_config:

instances:
  #
  # The HDFS NameNode check retrieves metrics from the HDFS NameNode's JMX
  # interface. This check must be installed on the NameNode. The HDFS
  # NameNode JMX URI is composed of the NameNode's hostname and port.
  #
  # The hostname and port can be found in the hdfs-site.xml conf file under
  # the property dfs.http.address or dfs.namenode.http-address
  #
  -  hdfs_namenode_jmx_uri: http://localhost:50070
```
**Steps to reproduce the issue:**
1. use the config above
2. restart datadog agent after upgrading to 5.22

**Describe the results you received:**

metrics collection failure

**Describe the results you expected:**

reading the connection string and collection of jmx hdfs metrics

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ferristseng** [comment]
I was running into this issue as well. It looks like it was fixed in a newer version:

https://github.com/DataDog/integrations-core/commit/638903b6e0fa3e2ee2e236d065b4a146f570fda5

**Comment by masci** [comment]
Thanks @ferristseng for pointing out. Closing as resolved, @sammerry feel free to reopen at https://github.com/DataDog/integrations-core/issues
