### ISSUE TITLE
Issue when parsing metrics containing "NaN" in the value field

### ISSUE THREAD

**Issue by mcpate** [DataDog/dd-agent#1790]
(note: this was originally opened in the datadogpy project but it was suggested that the issue is with dd-agent)

I have a Dropwizard project that ships a bunch of metrics to dogStatsD. When the app is initialized there are a few metrics that report "NaN" in the value field (this will happen until requests start coming in). I notice that during this time dogStatsD is throwing exceptions that then get logged (in our case, they get logged into SumoLogic which we are paying for by "space used").

It would be nice if dogStatsD handled this type of field since it is a part of the Java language specification. It seems that "NaN" should result in a value of 0 (in the case of the Dropwizard metrics, it is the case of "0.0d / 0.0") especially when being used for metrics.

This is the exception:
```
dd.dogstatsd[15]: ERROR (dogstatsd.py:308): Error receiving datagram
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 296, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 599, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 474, in parse_metric_packet
    raise Exception('Metric value must be a number: %s, %s' % (name, raw_value))
Exception: Metric value must be a number: cns.io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-5m, ?
```

**Comment by yannmh** [comment]
Thanks for re-opening the ticket here @mcpate.

We should indeed handle `NaN` values gracefully as part of the stastd specification. We'll work on a fix for the 5.5.0 agent release.

**Comment by yannmh** [comment]
Actually, `dogstatsd` correctly handles `NaN` values.  In fact, `NaN` can naturally be casted to `float` in Python:
```
>>> float('NaN')
nan
```

Coming back to the case,
>raise Exception('Metric value must be a number: %s, %s' % (name, raw_value))
Exception: Metric value must be a number: cns.io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-5m, ?

The issue, here, is that the value received is not a `NaN` symbol, but a question mark `?`. I reckon `NaN` is probably translated to `?` in the datagram packet submitted.

Would you be able to provide us more information that could help us understanding how your application is submitting those metrics to DogStatsd ?  Thank you

**Comment by mcpate** [comment]
Sure.  I'm happy to provide whatever might help.  These are the libraries I'm using for metrics/reporting:
```
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-metrics</artifactId>
            <version>${dropwizard.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <version>${metrics3.version}</version>
        </dependency>

        <dependency>
            <groupId>org.coursera</groupId>
            <artifactId>dropwizard-metrics-datadog</artifactId>
            <version>1.0.2</version>
        </dependency>

        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-core</artifactId>
            <version>1.4.7</version>
        </dependency>
```

It is good to know that the DogStatsD is parsing correctly.  I am now wondering if there is an issue with the way the org.coursera.dropwizard-metrics-datadog plugin is reporting...

**Comment by yannmh** [comment]
`org.coursera.dropwizard-metrics-datadog` plugin is using this [DogStatsD client for Java] (https://github.com/indeedeng/java-dogstatsd-client), as listed in its [pom file](https://github.com/coursera/metrics-datadog/blob/master/pom.xml#L155-L159).

I was able to confirm my hyopthesis. I think the `Double.NaN` is not correctly handled by the library. 
In particular, while it should probably be translated to a `nan` String, it becomes the unknown/unrepresentable character `�`.

```java
    @Test(timeout=5000L) public void
    sends_nan_gauge_to_statsd() throws Exception {
        client.recordGaugeValue("mygauge", Double.NaN);
        server.waitForMessage();

        assertThat(server.messagesReceived(), contains("my.prefix.mygauge:nan|g"));
    }
```
leads to
```
    [junit] Expected: iterable containing ["my.prefix.mygauge:nan|g"]
    [junit]      but: item 0: was "my.prefix.mygauge:�|g"
```

**Comment by mcpate** [comment]
Great find!  I can create a pull request with them if you haven't already?  Thanks a ton for working with me on this.  You guys have been great.

**Comment by yannmh** [comment]
That'd be great, thanks @mcpate ! I am closing this issue but please feel free to reach out if there is anything we can do to help.
